---
# tasks file for zfs
- name: Load the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Install the zfs packages
  package: 
    name: '{{ item }}'
    state: present
  with_items: '{{ zfs_pkgs }}'

- name: Configure zed daemon
  template: 
    src: zed.rc.j2
    dest: '/etc/zfs/zed.d/zed.rc'
    owner: root
    group: root
    mode: 0600
  notify: restart zed
  
